### ISSUE TITLE
problem about  processing of datasets in traffic Models

### ISSUE THREAD

**Issue by L-logic** [BNN-UPC/RouteNet-Erlang#12]
when i run main.py to train a model in this folder
![image](https://github.com/BNN-UPC/RouteNet-Erlang/assets/57951428/18e57fcf-d08d-470d-bc2c-7b5e758aa3c7)
，the program stopped and showed
![image](https://github.com/BNN-UPC/RouteNet-Erlang/assets/57951428/4a4f241f-83d1-4f56-b023-a5ebd3a15e51)
，the problem also occurs when i run  prediction.py, so i suppose that this problem may related to  processing of datasets .what's more, i  can only successfully  run scalability module well, so could u please give me some instruction on how to fix this problem???plz!

**Comment by MiquelFerriol** [comment]
Dear @L-logic,
This problem arises when the dataset fed to the model is empty. This is probably caused because the paths specified in [line 40](https://github.com/BNN-UPC/RouteNet-Erlang/blob/8e18010322da2fad10d9cf22d14d82b6be1c0857/TrafficModels/Delay/all_multiplexed/main.py#L40) and [line 45](https://github.com/BNN-UPC/RouteNet-Erlang/blob/8e18010322da2fad10d9cf22d14d82b6be1c0857/TrafficModels/Delay/all_multiplexed/main.py#L45) of the main.py file is not where the datasets are located. The same applies to the check_predictions file.

Please, double-check that these paths are correctly specified.

Bests,
Miquel

**Comment by L-logic** [comment]
Thank you very much for your answer. The question is exactly as you said
