### ISSUE TITLE
Request for Addition of Missing Poisson Distribution Code in Data Generation

### ISSUE THREAD

**Issue by MashiroSaber008** [BNN-UPC/RouteNet-Erlang#13]
Hi. I noticed that the training scripts in `TrafficModels` are intended to support five types of distributions as mentioned in the [paper.](https://ieeexplore.ieee.org/document/9796944). However, it appears that the segment for training data generated by Poisson distribution is missing.

Could you please provide the missing Poisson distribution training code?  The inclusion of this part would be immensely helpful for me and others in the community attempting to replicate your results fully.

Thank you for considering this request.  I look forward to the complete set of scripts.

**Comment by MiquelFerriol** [comment]
Dear @MashiroSaber008,

Thank you for bringing this to our attention!

You are correct in observing that the dataset/training code for the Poisson distribution is not currently included in our provided scripts. The datasets utilized for this experiment can be found [here](https://github.com/BNN-UPC/NetworkModelingDatasets/tree/master/datasets_v1). However, since these datasets are from an earlier version, some adjustments may be necessary to integrate them into the provided script.

While I am actively working on resolving this issue, you might find our newly released model, [RouteNet-Fermi](https://github.com/BNN-UPC/RouteNet-Fermi), interesting. In the Scalability section particularly, you'll find datasets featuring the Poisson distribution along with the corresponding scripts for training, validation, and testing.

Again, thank you for pointing this out.

Best regards,
Miquel
